"use client";

import { useState } from "react";
import { createEventAction } from "@/app/personal/actions";

type WorkspaceOption={id:string;name:string};
export function EventCreateModal({date,workspaces}:{date:string;workspaces:WorkspaceOption[]}){
  const [open,setOpen]=useState(false),[allDay,setAllDay]=useState(false);
  const [start,setStart]=useState(`${date}T09:00`),[end,setEnd]=useState(`${date}T10:00`);
  async function submit(data:FormData){await createEventAction(data);setOpen(false);}
  function toggle(value:boolean){setAllDay(value);setStart(value?start.slice(0,10):`${start.slice(0,10)}T09:00`);setEnd(value?end.slice(0,10):`${end.slice(0,10)}T10:00`);}
  return <><button type="button" className="day-add" onClick={()=>setOpen(true)} aria-label={`Add event on ${date}`}>+</button>{open&&<div className="modal-backdrop" onMouseDown={()=>setOpen(false)}><div className="event-modal" role="dialog" aria-modal="true" aria-label="Create calendar event" onMouseDown={(event)=>event.stopPropagation()}><div className="section-heading"><div><p className="eyebrow">NEW EVENT</p><h2>{date}</h2></div><button type="button" className="modal-close" onClick={()=>setOpen(false)}>×</button></div><form action={submit}><label><span>Title</span><input name="title" required autoFocus placeholder="Event title"/></label><label><span>Workspace</span><select name="workspaceId"><option value="">No workspace</option>{workspaces.map((workspace)=><option value={workspace.id} key={workspace.id}>{workspace.name}</option>)}</select></label><div className="modal-time-row"><label><span>Starts</span><input name="startsAt" type={allDay?"date":"datetime-local"} value={start} onChange={(e)=>setStart(e.target.value)} required/></label><label><span>Ends</span><input name="endsAt" type={allDay?"date":"datetime-local"} value={end} onChange={(e)=>setEnd(e.target.value)}/></label></div><div className="modal-time-row"><label><span>Repeat</span><select name="recurrence" defaultValue="NONE"><option value="NONE">Does not repeat</option><option value="YEARLY">Every year</option></select></label><label><span>Color</span><input name="color" type="color" defaultValue="#2563eb"/></label></div><label><span>Description</span><textarea name="description" placeholder="Optional details"/></label><label className="check-label"><input type="checkbox" name="allDay" checked={allDay} onChange={(e)=>toggle(e.target.checked)}/> All day</label><div className="editor-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancel</button><button>Create event</button></div></form></div></div>}</>;
}
