"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { moveWorkspaceBlockAction } from "@/app/pages/actions";
import type { WorkspaceBlock, WorkspacePage } from "@/lib/block-workspace-repository";
import type { WorkspaceBlockContent, WorkspaceBlockType } from "@/lib/block-workspace";

type SaveState="saved"|"saving"|"conflict"|"failed";
const label={saved:"저장됨",saving:"저장 중…",conflict:"다른 탭의 변경과 충돌",failed:"저장 실패"};
const editableTypes:{value:WorkspaceBlockType;label:string}[]=[{value:"PARAGRAPH",label:"텍스트"},{value:"HEADING",label:"제목"},{value:"BULLETED_LIST",label:"글머리 목록"},{value:"NUMBERED_LIST",label:"번호 목록"},{value:"TODO",label:"할 일"},{value:"CALLOUT",label:"콜아웃"},{value:"DIVIDER",label:"구분선"}];
function useAutosave(url:string,payload:unknown,initialVersion:number){const[state,setState]=useState<SaveState>("saved"),first=useRef(true),version=useRef(initialVersion),serialized=JSON.stringify(payload);useEffect(()=>{if(first.current){first.current=false;return;}setState("saving");const controller=new AbortController(),timer=setTimeout(async()=>{try{const response=await fetch(url,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({...JSON.parse(serialized),version:version.current}),signal:controller.signal});if(response.status===409)return setState("conflict");if(!response.ok)return setState("failed");version.current=Number((await response.json()).version);setState("saved");}catch{if(!controller.signal.aborted)setState("failed");}},600);return()=>{clearTimeout(timer);controller.abort();};},[url,serialized]);return state;}
function contentFor(type:WorkspaceBlockType,text:string):WorkspaceBlockContent{if(type==="HEADING")return{text,level:2};if(type==="TODO")return{text,checked:false};if(type==="CALLOUT")return{text,color:"default"};if(type==="DIVIDER")return{};return{text};}
function BlockEditor({pageId,block}:{pageId:string;block:WorkspaceBlock}){const router=useRouter(),[type,setType]=useState(block.type),[content,setContent]=useState(block.content),[slashOpen,setSlashOpen]=useState(false),text=content.text??"",state=useAutosave(`/api/pages/${pageId}/blocks/${block.id}`,{type,content},block.version);const addAfter=async()=>{const response=await fetch(`/api/pages/${pageId}/blocks`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({afterBlockId:block.id})});if(response.ok){const blockId=(await response.json()).blockId;window.location.hash=`block-${blockId}`;router.refresh();}};const remove=async()=>{if((await fetch(`/api/pages/${pageId}/blocks/${block.id}`,{method:"DELETE"})).ok)router.refresh();};const changeType=(next:WorkspaceBlockType)=>{setType(next);setContent(contentFor(next,text==="/"?"":text));setSlashOpen(false);};useEffect(()=>{if(window.location.hash===`#block-${block.id}`)document.getElementById(`input-${block.id}`)?.focus();},[block.id]);return <div className={`workspace-block type-${type.toLowerCase()}`} id={`block-${block.id}`}><div className="workspace-block-toolbar"><select value={type} onChange={event=>changeType(event.target.value as WorkspaceBlockType)}>{editableTypes.map(item=><option value={item.value} key={item.value}>{item.label}</option>)}</select><form action={moveWorkspaceBlockAction}><input type="hidden" name="pageId" value={pageId}/><input type="hidden" name="blockId" value={block.id}/><button name="direction" value="up" aria-label="블록 위로">↑</button><button name="direction" value="down" aria-label="블록 아래로">↓</button></form><button type="button" onClick={remove} aria-label="블록 삭제">×</button></div>{type==="DIVIDER"?<hr/>:<div className="workspace-block-input">{type==="TODO"&&<input type="checkbox" checked={content.checked??false} onChange={event=>setContent({...content,checked:event.target.checked})}/>}<textarea id={`input-${block.id}`} value={text} onChange={event=>{const value=event.target.value;setContent({...content,text:value});setSlashOpen(type==="PARAGRAPH"&&value==="/");}} onKeyDown={event=>{if(event.key==="Escape")setSlashOpen(false);if(event.key==="Enter"&&!event.shiftKey&&!slashOpen){event.preventDefault();void addAfter();}}} placeholder="내용을 입력하세요. / 로 블록 선택" aria-label={`${type} 블록`}/>{slashOpen&&<div className="workspace-slash-menu" role="menu" aria-label="블록 종류 선택">{editableTypes.map(item=><button type="button" role="menuitem" onClick={()=>changeType(item.value)} key={item.value}>{item.label}</button>)}</div>}</div>}<small className={`save-${state}`}>{label[state]}</small></div>;}
export function WorkspacePageEditor({page}:{page:WorkspacePage}){const[title,setTitle]=useState(page.title),state=useAutosave(`/api/pages/${page.id}`,{title},page.version);return <div className="workspace-editor"><div className="workspace-title"><input value={title} onChange={event=>setTitle(event.target.value)} placeholder="제목 없음" aria-label="페이지 제목"/><small className={`save-${state}`}>{label[state]}</small></div>{page.blocks.map(block=><BlockEditor pageId={page.id} block={block} key={block.id}/>)}</div>;}
