import { createEventAction } from "@/app/personal/actions";
import { listCalendarEvents, listTasks, listWorkspaces } from "@/lib/automation-repository";

export const dynamic="force-dynamic";
const pad=(n:number)=>String(n).padStart(2,"0");
const seoulKey=(value:string)=>{const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date(value));const get=(type:string)=>parts.find((p)=>p.type===type)?.value;return `${get("year")}-${get("month")}-${get("day")}`;};
export default async function CalendarPage({searchParams}:{searchParams:Promise<{month?:string}>}){const requested=(await searchParams).month;const now=new Date();const match=requested?.match(/^(\d{4})-(\d{2})$/);const year=match?Number(match[1]):now.getFullYear();const month=match?Number(match[2])-1:now.getMonth();const first=new Date(Date.UTC(year,month,1));const last=new Date(Date.UTC(year,month+1,1));const gridStart=new Date(first);gridStart.setUTCDate(1-first.getUTCDay());const gridEnd=new Date(last);gridEnd.setUTCDate(last.getUTCDate()+(7-last.getUTCDay())%7);const [events,tasks,workspaces]=await Promise.all([listCalendarEvents(gridStart.toISOString(),gridEnd.toISOString()),listTasks(),listWorkspaces()]);const previous=new Date(Date.UTC(year,month-1,1)),next=new Date(Date.UTC(year,month+1,1));const days=[];for(let d=new Date(gridStart);d<gridEnd;d.setUTCDate(d.getUTCDate()+1))days.push(new Date(d));const dateKey=(d:Date)=>`${d.getUTCFullYear()}-${pad(d.getUTCMonth()+1)}-${pad(d.getUTCDate())}`;return <><header className="page-head"><div><p className="eyebrow">PERSONAL</p><h1>Calendar</h1><p>See personal events and Task due dates in one monthly view.</p></div></header>
  <form action={createEventAction} className="event-create"><input name="title" required placeholder="Event title"/><select name="workspaceId"><option value="">No workspace</option>{workspaces.map((w)=><option value={w.id} key={w.id}>{w.name}</option>)}</select><input name="startsAt" type="datetime-local" required/><input name="endsAt" type="datetime-local"/><input name="description" placeholder="Description"/><label className="check-label"><input type="checkbox" name="allDay"/> All day</label><button>Add event</button></form>
  <div className="calendar-head"><a href={`/calendar?month=${dateKey(previous).slice(0,7)}`}>← Previous</a><h2>{first.toLocaleDateString("en-US",{month:"long",year:"numeric",timeZone:"UTC"})}</h2><a href={`/calendar?month=${dateKey(next).slice(0,7)}`}>Next →</a></div><div className="week-labels">{"Sun Mon Tue Wed Thu Fri Sat".split(" ").map((v)=><span key={v}>{v}</span>)}</div><section className="calendar-grid">{days.map((day)=>{const key=dateKey(day);const dayEvents=events.filter((e)=>seoulKey(e.startsAt)===key);const dueTasks=tasks.filter((t)=>t.dueAt&&seoulKey(t.dueAt)===key);return <article className={day.getUTCMonth()===month?"":"outside"} key={key}><strong>{day.getUTCDate()}</strong>{dayEvents.map((e)=><a href={`/calendar/events/${e.id}`} className="calendar-item event" key={e.id}>{e.allDay?"All day":new Date(e.startsAt).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Seoul"})} · {e.title}</a>)}{dueTasks.map((t)=><a href={`/automation/tasks/${t.id}`} className="calendar-item task" key={t.id}>Due · {t.title}</a>)}</article>})}</section></>}
