const baseUrl=document.querySelector("#baseUrl"),token=document.querySelector("#token"),ownerBlogId=document.querySelector("#ownerBlogId"),status=document.querySelector("#status");
chrome.storage.local.get(["baseUrl","token","ownerBlogId"],saved=>{if(saved.baseUrl)baseUrl.value=saved.baseUrl;if(saved.token)token.value=saved.token;if(saved.ownerBlogId)ownerBlogId.value=saved.ownerBlogId;});
document.querySelector("#save").addEventListener("click",async()=>{await chrome.storage.local.set({baseUrl:baseUrl.value.replace(/\/+$/,""),token:token.value,ownerBlogId:ownerBlogId.value.trim().toLowerCase()});status.textContent="설정을 저장했어요.";});
async function extractCommentsAfterOpening(ownerId){
  const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const controls=[...document.querySelectorAll("button, a")].filter(element=>/댓글/.test(element.textContent||"")||/comment/i.test(element.className||""));
  for(const control of controls.slice(0,30)){if(control.getClientRects().length)try{control.click();}catch{}}
  if(controls.length)await wait(900);
  const postUrl=(document.querySelector('link[rel="canonical"]')?.href||location.href).replace(/^http:/,"https:");
  const containers=[...document.querySelectorAll(".u_cbox_comment_box, .comment_item, [class*='CommentItem']")];
  const parseDate=raw=>{const direct=Date.parse(raw);if(!Number.isNaN(direct))return new Date(direct).toISOString();const normalized=raw.replace(/\.\s*/g,"-").replace(/-\s+(\d{1,2}:\d{2})/," $1").replace(/-\s*$/," ").trim();const parsed=Date.parse(normalized);return Number.isNaN(parsed)?null:new Date(parsed).toISOString();};
  const keyFromHref=href=>{try{const url=new URL(href),path=url.pathname.split("/").filter(Boolean);return(url.searchParams.get("blogId")||url.searchParams.get("userId")||path[0]||"").toLowerCase();}catch{return"";}};
  const pending=[],replied=[];
  for(const element of containers.filter(item=>item.getClientRects().length>0&&!item.closest(".u_cbox_reply_area, [class*='reply_area']"))){const text=selector=>element.querySelector(selector)?.textContent?.trim()||"",rawDate=text(".u_cbox_date, .comment_info_date, [class*='date']"),article=element.closest("article, [class*='post'], [class*='Post']"),link=article?.querySelector("a[href*='logNo='], a[href*='PostView'], a[href*='blog.naver.com']")?.href,item={postUrl:(link||postUrl).replace(/^http:/,"https:"),commenter:text(".u_cbox_nick, .comment_nickname, [class*='nickname'], [class*='name']"),commentExcerpt:text(".u_cbox_contents, .comment_text, [class*='content']").slice(0,500),commentedAt:parseDate(rawDate)};if(!item.commenter||!item.commentExcerpt||!item.commentedAt)continue;const thread=element.closest(".u_cbox_comment, li, [class*='CommentItem']")||element.parentElement,replyLinks=[...(thread?.querySelectorAll(".u_cbox_reply_area a[href], [class*='reply'] a[href], [class*='Reply'] a[href]")||[])],hasOwnerReply=Boolean(ownerId)&&replyLinks.some(anchor=>keyFromHref(anchor.href)===ownerId);(hasOwnerReply?replied:pending).push(item);}
  return{pending,replied};
}
async function extractNeighbors(){
  const selected=[...document.querySelectorAll("[aria-current='page'], [aria-selected='true'], .on, .selected, .active")].map(item=>item.textContent||"").join(" "),urlText=location.href;
  const scope=/나를\s*추가한\s*이웃/.test(selected)||/[?&](?:type|relation|tab)=(?:follower|addedme)/i.test(urlText)?"FOLLOWERS":/내가\s*추가한\s*이웃/.test(selected)||/[?&](?:type|relation|tab)=(?:following|mybuddy)/i.test(urlText)?"FOLLOWING":/서로이웃\s*신청/.test(selected)||/request|apply/i.test(urlText)?"REQUESTS":null;
  if(!scope)return{neighbors:[],completeSnapshot:false,scope:null,pages:0};
  const parse=(doc,pageUrl)=>{const values=[];for(const row of doc.querySelectorAll("li, tr, [class*='buddy'], [class*='neighbor']")){const anchor=[...row.querySelectorAll("a[href]")].find(item=>/blog\.naver\.com/.test(item.getAttribute("href")||""));if(!anchor)continue;let url;try{url=new URL(anchor.getAttribute("href"),pageUrl);}catch{continue;}const key=(url.searchParams.get("blogId")||url.pathname.split("/").filter(Boolean)[0]||"").toLowerCase();if(!/^[a-z0-9_.-]+$/i.test(key))continue;const text=(row.textContent||"").replace(/\s+/g," ").trim(),relation=scope==="REQUESTS"?(/받은\s*(?:신청|서로이웃)|신청\s*받/i.test(text)?"INCOMING_PENDING":"OUTGOING_PENDING"):/서로\s*이웃|서이/i.test(text)?"MUTUAL":scope==="FOLLOWERS"?"FOLLOWER":"FOLLOWING",name=(row.querySelector("[class*='name'], [class*='nick'], strong")?.textContent||anchor.textContent||key).trim();values.push({bloggerKey:key,bloggerName:name,blogUrl:`https://blog.naver.com/${encodeURIComponent(key)}`,relation});}return values;};
  const pageLinks=(doc,pageUrl)=>[...doc.querySelectorAll("a[href]")].flatMap(anchor=>{const label=(anchor.textContent||"").trim(),raw=anchor.getAttribute("href")||"";if(!/^(?:\d+|다음|next|›|»)>?$/i.test(label)&&!/page(?:No)?=/i.test(raw))return[];try{const url=new URL(raw,pageUrl);return url.origin===location.origin&&/buddy|neighbor/i.test(url.href)?[url.href]:[];}catch{return[];}});
  const queue=[location.href],visited=new Set(),values=[];let complete=true;
  while(queue.length&&visited.size<100){const pageUrl=queue.shift();if(visited.has(pageUrl))continue;visited.add(pageUrl);try{const doc=pageUrl===location.href?document:new DOMParser().parseFromString(await(await fetch(pageUrl,{credentials:"include"})).text(),"text/html");values.push(...parse(doc,pageUrl));for(const link of pageLinks(doc,pageUrl))if(!visited.has(link))queue.push(link);}catch{complete=false;}}
  if(queue.length)complete=false;
  return{neighbors:[...new Map(values.map(item=>[item.bloggerKey,item])).values()],completeSnapshot:complete&&values.length>0,scope,pages:visited.size};
}
function extractGrowth(){
  const number=value=>{const match=String(value||"").replaceAll(",","").match(/\d+/);return match?Number(match[0]):null;};
  const find=labels=>{for(const element of document.querySelectorAll("dt, dd, th, td, li, div, span")){const text=(element.textContent||"").replace(/\s+/g," ").trim();if(text.length>80||!labels.some(label=>text.includes(label)))continue;const own=number(text.replace(new RegExp(labels.join("|"),"g"),""));if(own!==null)return own;const container=element.closest("li, tr, dl, [class*='item'], [class*='stat']");const nearby=number(container?.textContent);if(nearby!==null)return nearby;}return null;};
  const selectedDate=document.querySelector("input[type='date']")?.value||document.querySelector("time[datetime]")?.getAttribute("datetime")?.slice(0,10),today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
  return{measuredOn:/^\d{4}-\d{2}-\d{2}$/.test(selectedDate||"")?selectedDate:today,visitors:find(["방문자","순방문자"]),views:find(["조회수","페이지뷰"]),posts:find(["전체글","게시글"])};
}
async function settings(){const saved=await chrome.storage.local.get(["baseUrl","token","ownerBlogId"]);if(!saved.baseUrl||!saved.token){status.textContent="Mano 주소와 토큰을 먼저 저장해 주세요.";return null;}return saved;}
async function activeNaverTab(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});let allowed=false;try{const url=new URL(tab?.url||"");allowed=url.protocol==="https:"&&(url.hostname==="blog.naver.com"||url.hostname.endsWith(".blog.naver.com"));}catch{}if(!tab?.id||!allowed){status.textContent="네이버 블로그 화면에서 실행해 주세요.";return null;}return tab;}
async function send(path,body){const saved=await settings();if(!saved)return null;const response=await fetch(`${saved.baseUrl}${path}`,{method:"POST",headers:{authorization:`Bearer ${saved.token}`,"content-type":"application/json"},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);return result;}
document.querySelector("#collect").addEventListener("click",async()=>{status.textContent="댓글 영역을 자동으로 열고 확인하는 중…";const saved=await settings();if(!saved)return;if(!/^[a-z0-9_.-]+$/i.test(saved.ownerBlogId||"")){status.textContent="내 네이버 블로그 ID를 먼저 저장해 주세요.";return;}const tab=await activeNaverTab();if(!tab)return;try{const frames=await chrome.scripting.executeScript({target:{tabId:tab.id,allFrames:true},func:extractCommentsAfterOpening,args:[saved.ownerBlogId]}),pending=new Map(),replied=new Map();for(const frame of frames){for(const item of frame.result?.pending||[])pending.set([item.postUrl,item.commenter,item.commentedAt,item.commentExcerpt].join("|"),item);for(const item of frame.result?.replied||[])replied.set([item.postUrl,item.commenter,item.commentedAt,item.commentExcerpt].join("|"),item);}const comments=[...pending.values()],repliedComments=[...replied.values()];if(!comments.length&&!repliedComments.length){status.textContent="현재 화면에서 댓글을 찾지 못했어요. 글 본문이 보이는지 확인해 주세요.";return;}const result=await send("/api/integrations/blog/replies",{comments,repliedComments});if(result)status.textContent=`미답글 ${result.accepted}개 추가 · 기존 ${result.completed}개 완료 처리 · ${result.skipped}개 중복/제외`;}catch(error){status.textContent=`댓글 수집 실패: ${error.message}`;}});
document.querySelector("#neighbors").addEventListener("click",async()=>{status.textContent="현재 이웃 탭의 모든 페이지를 확인하는 중…";const tab=await activeNaverTab();if(!tab)return;try{const frames=await chrome.scripting.executeScript({target:{tabId:tab.id,allFrames:true},func:extractNeighbors}),resultFrame=frames.map(frame=>frame.result).find(result=>result?.scope);if(!resultFrame){status.textContent="선택된 이웃 관리 탭을 인식하지 못했어요.";return;}const result=await send("/api/integrations/blog/neighbors",resultFrame);if(result)status.textContent=`${resultFrame.pages}페이지 · ${result.accepted}명 동기화 · 이 탭에서 사라진 관계 ${result.missing}명`;}catch(error){status.textContent=`이웃 동기화 실패: ${error.message}`;}});
document.querySelector("#growth").addEventListener("click",async()=>{status.textContent="성장 지표를 확인하는 중…";const tab=await activeNaverTab();if(!tab)return;try{const frames=await chrome.scripting.executeScript({target:{tabId:tab.id,allFrames:true},func:extractGrowth}),growth=(frames.map(frame=>frame.result).filter(Boolean).sort((a,b)=>[b.visitors,b.views,b.posts].filter(value=>value!==null).length-[a.visitors,a.views,a.posts].filter(value=>value!==null).length)[0]);if(!growth||[growth.visitors,growth.views,growth.posts].every(value=>value===null)){status.textContent="지표를 찾지 못했어요. 네이버 통계 화면이나 내 블로그 홈에서 실행해 주세요.";return;}const result=await send("/api/integrations/blog/growth",growth);if(result?.saved)status.textContent=`${growth.measuredOn} 성장 지표를 저장했어요.`;}catch(error){status.textContent=`성장 지표 수집 실패: ${error.message}`;}});
