import { db } from "@/lib/db";
import type { Approval, Artifact, AutomationRun, CalendarEvent, Note, Task, TaskDetails, TaskReference, TaskStatus, Workspace, WorkspaceEditableDetails, WorkspaceLink, WorkspacePostit, WorkspaceTodoCategory } from "@/lib/automation-types";

export async function listWorkspaces(): Promise<Workspace[]> {
  const { rows } = await db.query(`SELECT w.id,w.slug,w.name,w.description,w.links,w.details,count(t.id)::int AS task_count FROM workspaces w LEFT JOIN tasks t ON t.workspace_id=w.id GROUP BY w.id ORDER BY w.name`);
  return rows.map((r) => ({ id:r.id,slug:r.slug,name:r.name,description:r.description,links:r.links,details:r.details??{},taskCount:r.task_count }));
}

export async function updateWorkspace(id:string,input:{name:string;description:string;links:WorkspaceLink[];details:WorkspaceEditableDetails}){const r=await db.query(`UPDATE workspaces SET name=$2,description=$3,links=$4::jsonb,details=$5::jsonb WHERE id=$1`,[id,input.name,input.description,JSON.stringify(input.links),JSON.stringify(input.details)]);return r.rowCount===1;}
export async function listWorkspacePostits(workspaceId:string):Promise<WorkspacePostit[]>{const {rows}=await db.query(`SELECT * FROM workspace_postits WHERE workspace_id=$1 ORDER BY updated_at DESC`,[workspaceId]);return rows.map((r)=>({id:r.id,workspaceId:r.workspace_id,categoryId:r.category_id,title:r.title,content:r.content,color:r.color,updatedAt:r.updated_at.toISOString()}));}
export async function createWorkspacePostit(input:{workspaceId:string;categoryId:string|null;title:string;content:string;color:string}){await db.query(`INSERT INTO workspace_postits(workspace_id,category_id,title,content,color) VALUES($1,$2,$3,$4,$5)`,[input.workspaceId,input.categoryId,input.title,input.content,input.color]);}
export async function updateWorkspacePostit(id:string,input:{categoryId:string|null;title:string;content:string;color:string}){await db.query(`UPDATE workspace_postits SET category_id=$2,title=$3,content=$4,color=$5,updated_at=now() WHERE id=$1`,[id,input.categoryId,input.title,input.content,input.color]);}
export async function deleteWorkspacePostit(id:string){await db.query(`DELETE FROM workspace_postits WHERE id=$1`,[id]);}
export async function listWorkspaceTodoCategories(workspaceId:string):Promise<WorkspaceTodoCategory[]>{const {rows}=await db.query(`SELECT c.id,c.workspace_id,c.name,COALESCE(json_agg(json_build_object('id',t.id,'categoryId',t.category_id,'title',t.title,'description',t.description,'completed',t.completed) ORDER BY t.created_at) FILTER (WHERE t.id IS NOT NULL),'[]') AS todos FROM workspace_todo_categories c LEFT JOIN workspace_todos t ON t.category_id=c.id WHERE c.workspace_id=$1 GROUP BY c.id ORDER BY c.created_at`,[workspaceId]);return rows;}
export async function createWorkspaceTodoCategory(workspaceId:string,name:string){await db.query(`INSERT INTO workspace_todo_categories(workspace_id,name) VALUES($1,$2)`,[workspaceId,name]);}
export async function deleteWorkspaceTodoCategory(id:string){await db.query(`DELETE FROM workspace_todo_categories WHERE id=$1`,[id]);}
export async function createWorkspaceTodo(categoryId:string,title:string,description:string){await db.query(`INSERT INTO workspace_todos(category_id,title,description) VALUES($1,$2,$3)`,[categoryId,title,description]);}
export async function updateWorkspaceTodoCompleted(id:string,completed:boolean){await db.query(`UPDATE workspace_todos SET completed=$2,updated_at=now() WHERE id=$1`,[id,completed]);}
export async function deleteWorkspaceTodo(id:string){await db.query(`DELETE FROM workspace_todos WHERE id=$1`,[id]);}

function mapTask(row: any, artifacts: Artifact[]): Task {
  return { id:row.id,workspaceId:row.workspace_id,workspaceSlug:row.workspace_slug,workspaceName:row.workspace_name,title:row.title,description:row.description,taskType:row.task_type,status:row.status,priority:row.priority,inputNotes:row.input_notes,resultText:row.result_text,references:row.reference_items??[],details:row.details??{},dueAt:row.due_at?.toISOString()??null,createdAt:row.created_at.toISOString(),updatedAt:row.updated_at.toISOString(),artifacts:artifacts.filter((a)=>a.taskId===row.id) };
}

export async function listTasks(workspaceSlug?: string): Promise<Task[]> {
  const [{ rows }, artifacts] = await Promise.all([
    db.query(`SELECT t.*,w.slug AS workspace_slug,w.name AS workspace_name FROM tasks t JOIN workspaces w ON w.id=t.workspace_id ${workspaceSlug?"WHERE w.slug=$1":""} ORDER BY t.updated_at DESC`,workspaceSlug?[workspaceSlug]:[]), listArtifacts(),
  ]);
  return rows.map((r)=>mapTask(r,artifacts));
}

export async function getTask(id:string):Promise<Task|null> {
  const [{rows},artifacts]=await Promise.all([db.query(`SELECT t.*,w.slug AS workspace_slug,w.name AS workspace_name FROM tasks t JOIN workspaces w ON w.id=t.workspace_id WHERE t.id=$1`,[id]),listArtifacts(id)]);
  return rows[0]?mapTask(rows[0],artifacts):null;
}

export async function createTask(input:{workspaceId:string;title:string;description:string;priority:string}) {
  const {rows}=await db.query(`INSERT INTO tasks(workspace_id,title,description,priority,task_type) SELECT id,$2,$3,$4,CASE WHEN slug='blog' THEN 'BLOG' WHEN slug IN ('project-a','project-t') THEN 'PROJECT' ELSE 'GENERAL' END FROM workspaces WHERE id=$1 RETURNING id`,[input.workspaceId,input.title,input.description,input.priority]);
  return rows[0]?.id as string|undefined;
}
export async function updateTaskStatus(id:string,status:TaskStatus) { const r=await db.query("UPDATE tasks SET status=$2,updated_at=now() WHERE id=$1",[id,status]);return r.rowCount===1; }
export async function updateTaskContent(id:string,input:{title:string;description:string;priority:string;inputNotes:string;resultText:string;references:TaskReference[];details:TaskDetails;dueAt:string|null}) { const r=await db.query(`UPDATE tasks SET title=$2,description=$3,priority=$4,input_notes=$5,result_text=$6,reference_items=$7::jsonb,details=$8::jsonb,due_at=$9,updated_at=now() WHERE id=$1`,[id,input.title,input.description,input.priority,input.inputNotes,input.resultText,JSON.stringify(input.references),JSON.stringify(input.details),input.dueAt]);return r.rowCount===1; }

export async function listApprovals():Promise<Approval[]> { const {rows}=await db.query(`SELECT a.*,t.title AS task_title,w.name AS workspace_name FROM approvals a JOIN tasks t ON t.id=a.task_id JOIN workspaces w ON w.id=t.workspace_id ORDER BY a.requested_at DESC`);return rows.map((r)=>({id:r.id,taskId:r.task_id,taskTitle:r.task_title,workspaceName:r.workspace_name,status:r.status,note:r.note,requestedAt:r.requested_at.toISOString(),decidedAt:r.decided_at?.toISOString()??null})); }
export async function decideApproval(id:string,decision:"approved"|"rejected") { const c=await db.connect();try{await c.query("BEGIN");const {rows}=await c.query(`UPDATE approvals SET status=$2,decided_at=now() WHERE id=$1 AND status='pending' RETURNING task_id`,[id,decision]);if(!rows[0]){await c.query("ROLLBACK");return false;}await c.query("UPDATE tasks SET status=$2,updated_at=now() WHERE id=$1",[rows[0].task_id,decision==="approved"?"IN_PROGRESS":"DRAFT"]);await c.query("COMMIT");return true;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();} }
export async function listRuns():Promise<AutomationRun[]> { const {rows}=await db.query(`SELECT r.*,t.title AS task_title,w.name AS workspace_name FROM automation_runs r JOIN tasks t ON t.id=r.task_id JOIN workspaces w ON w.id=t.workspace_id ORDER BY r.started_at DESC`);return rows.map((r)=>({id:r.id,taskId:r.task_id,taskTitle:r.task_title,workspaceName:r.workspace_name,status:r.status,workflowRef:r.workflow_ref,summary:r.summary,startedAt:r.started_at.toISOString(),finishedAt:r.finished_at?.toISOString()??null})); }
export async function createRun(input:{taskId:string;status?:string;workflowRef?:string;summary?:string}) { const {rows}=await db.query(`INSERT INTO automation_runs(task_id,status,workflow_ref,summary) VALUES($1,$2,$3,$4) RETURNING id`,[input.taskId,input.status??"queued",input.workflowRef??null,input.summary??""]);return rows[0].id as string; }
export async function updateRun(id:string,input:{status:string;summary?:string}) { const r=await db.query(`UPDATE automation_runs SET status=$2,summary=COALESCE($3,summary),finished_at=CASE WHEN $2 IN ('succeeded','failed') THEN now() ELSE finished_at END WHERE id=$1`,[id,input.status,input.summary??null]);return r.rowCount===1; }
export async function listArtifacts(taskId?:string):Promise<Artifact[]> { const {rows}=await db.query(`SELECT id,task_id,run_id,name,path,kind FROM artifacts ${taskId?"WHERE task_id=$1":""} ORDER BY created_at DESC`,taskId?[taskId]:[]);return rows.map((r)=>({id:r.id,taskId:r.task_id,runId:r.run_id,name:r.name,path:r.path,kind:r.kind})); }

function mapNote(r:any):Note{return{id:r.id,workspaceId:r.workspace_id,workspaceName:r.workspace_name,title:r.title,body:r.body,tags:r.tags??[],isPinned:r.is_pinned,createdAt:r.created_at.toISOString(),updatedAt:r.updated_at.toISOString()};}
export async function listNotes(query?:string,workspace?:string):Promise<Note[]>{const values:string[]=[];const where:string[]=[];if(query){values.push(`%${query}%`);where.push(`(n.title ILIKE $${values.length} OR n.body ILIKE $${values.length} OR array_to_string(n.tags,' ') ILIKE $${values.length})`);}if(workspace){values.push(workspace);where.push(`w.slug=$${values.length}`);}const {rows}=await db.query(`SELECT n.*,w.name AS workspace_name FROM notes n LEFT JOIN workspaces w ON w.id=n.workspace_id ${where.length?`WHERE ${where.join(" AND ")}`:""} ORDER BY n.is_pinned DESC,n.updated_at DESC`,values);return rows.map(mapNote);}
export async function getNote(id:string):Promise<Note|null>{const {rows}=await db.query(`SELECT n.*,w.name AS workspace_name FROM notes n LEFT JOIN workspaces w ON w.id=n.workspace_id WHERE n.id=$1`,[id]);return rows[0]?mapNote(rows[0]):null;}
export async function createNote(input:{workspaceId:string|null;title:string;body:string;tags:string[]}){const {rows}=await db.query(`INSERT INTO notes(workspace_id,title,body,tags) VALUES($1,$2,$3,$4) RETURNING id`,[input.workspaceId,input.title,input.body,input.tags]);return rows[0].id as string;}
export async function updateNote(id:string,input:{workspaceId:string|null;title:string;body:string;tags:string[];isPinned:boolean}){const r=await db.query(`UPDATE notes SET workspace_id=$2,title=$3,body=$4,tags=$5,is_pinned=$6,updated_at=now() WHERE id=$1`,[id,input.workspaceId,input.title,input.body,input.tags,input.isPinned]);return r.rowCount===1;}
export async function deleteNote(id:string){const r=await db.query("DELETE FROM notes WHERE id=$1",[id]);return r.rowCount===1;}

function mapEvent(r:any):CalendarEvent{return{id:r.id,workspaceId:r.workspace_id,workspaceName:r.workspace_name,title:r.title,description:r.description,startsAt:r.starts_at.toISOString(),endsAt:r.ends_at?.toISOString()??null,allDay:r.all_day,recurrence:r.recurrence,color:r.color,completed:r.completed};}
export async function listCalendarEvents(from:string,to:string):Promise<CalendarEvent[]>{const {rows}=await db.query(`SELECT e.*,w.name AS workspace_name FROM calendar_events e LEFT JOIN workspaces w ON w.id=e.workspace_id WHERE (e.starts_at<$2 AND COALESCE(e.ends_at,e.starts_at)>=$1) OR e.recurrence='YEARLY' ORDER BY e.starts_at`,[from,to]);return rows.map(mapEvent);}
export async function getCalendarEvent(id:string):Promise<CalendarEvent|null>{const {rows}=await db.query(`SELECT e.*,w.name AS workspace_name FROM calendar_events e LEFT JOIN workspaces w ON w.id=e.workspace_id WHERE e.id=$1`,[id]);return rows[0]?mapEvent(rows[0]):null;}
export async function createCalendarEvent(input:{workspaceId:string|null;title:string;description:string;startsAt:string;endsAt:string|null;allDay:boolean;recurrence:string;color:string}){const {rows}=await db.query(`INSERT INTO calendar_events(workspace_id,title,description,starts_at,ends_at,all_day,recurrence,color) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id`,[input.workspaceId,input.title,input.description,input.startsAt,input.endsAt,input.allDay,input.recurrence,input.color]);return rows[0].id as string;}
export async function updateCalendarEvent(id:string,input:{workspaceId:string|null;title:string;description:string;startsAt:string;endsAt:string|null;allDay:boolean;recurrence:string;color:string}){const r=await db.query(`UPDATE calendar_events SET workspace_id=$2,title=$3,description=$4,starts_at=$5,ends_at=$6,all_day=$7,recurrence=$8,color=$9,updated_at=now() WHERE id=$1`,[id,input.workspaceId,input.title,input.description,input.startsAt,input.endsAt,input.allDay,input.recurrence,input.color]);return r.rowCount===1;}
export async function updateCalendarEventCompleted(id:string,completed:boolean){const r=await db.query(`UPDATE calendar_events SET completed=$2,updated_at=now() WHERE id=$1`,[id,completed]);return r.rowCount===1;}
export async function deleteCalendarEvent(id:string){const r=await db.query("DELETE FROM calendar_events WHERE id=$1",[id]);return r.rowCount===1;}
export async function listUpcoming(limit=5){const [events,tasks]=await Promise.all([db.query(`SELECT e.id,e.title,e.starts_at,w.name AS workspace_name FROM calendar_events e LEFT JOIN workspaces w ON w.id=e.workspace_id WHERE e.starts_at>=date_trunc('day',now()) ORDER BY e.starts_at LIMIT $1`,[limit]),db.query(`SELECT t.id,t.title,t.due_at,w.name AS workspace_name FROM tasks t JOIN workspaces w ON w.id=t.workspace_id WHERE t.due_at>=date_trunc('day',now()) AND t.status<>'DONE' ORDER BY t.due_at LIMIT $1`,[limit])]);return{events:events.rows.map((r)=>({...r,startsAt:r.starts_at.toISOString()})),tasks:tasks.rows.map((r)=>({...r,dueAt:r.due_at.toISOString()}))};}
