import {randomInt,randomUUID} from "node:crypto";
import {db} from "@/lib/db";
import {recordAdminError} from "@/lib/admin-errors";

export type BlogDiscoveryItem={id:string;url:string;title:string;bloggerName:string;excerpt:string;publishedOn:string|null;status:"NEW"|"DONE"};
const clean=(text:string)=>text.replace(/<[^>]*>/g,"").replaceAll("&quot;",'"').replaceAll("&amp;","&").replaceAll("&lt;","<").replaceAll("&gt;",">").replaceAll("&#39;", "'").trim();

export async function getBlogDiscovery(workspaceId:string){const [settingsResult,itemsResult]=await Promise.all([db.query(`SELECT keywords,last_keyword,last_error FROM blog_discovery_settings WHERE workspace_id=$1`,[workspaceId]),db.query(`SELECT id,url,title,blogger_name,excerpt,published_on,status FROM blog_discovery_items WHERE workspace_id=$1 AND batch_id=(SELECT current_batch FROM blog_discovery_settings WHERE workspace_id=$1) AND status<>'HIDDEN' ORDER BY published_on DESC NULLS LAST,created_at DESC`,[workspaceId])]);const settings=settingsResult.rows[0];return{configured:Boolean(process.env.NAVER_SEARCH_CLIENT_ID&&process.env.NAVER_SEARCH_CLIENT_SECRET),keywords:(settings?.keywords??[]) as string[],lastKeyword:settings?.last_keyword??"",error:settings?.last_error??"",items:itemsResult.rows.map((r):BlogDiscoveryItem=>({id:r.id,url:r.url,title:r.title,bloggerName:r.blogger_name,excerpt:r.excerpt,publishedOn:r.published_on?String(r.published_on).slice(0,10):null,status:r.status}))};}
export async function saveBlogDiscoveryKeywords(workspaceId:string,keywords:string[]){await db.query(`INSERT INTO blog_discovery_settings(workspace_id,keywords) SELECT id,$2 FROM workspaces WHERE id=$1 AND slug='blog' ON CONFLICT(workspace_id) DO UPDATE SET keywords=EXCLUDED.keywords,last_error='',updated_at=now()`,[workspaceId,keywords]);}
export async function rerollBlogDiscovery(workspaceId:string){const {rows}=await db.query(`SELECT keywords FROM blog_discovery_settings s JOIN workspaces w ON w.id=s.workspace_id WHERE s.workspace_id=$1 AND w.slug='blog'`,[workspaceId]),keywords=(rows[0]?.keywords??[]) as string[],clientId=process.env.NAVER_SEARCH_CLIENT_ID?.trim(),clientSecret=process.env.NAVER_SEARCH_CLIENT_SECRET?.trim();if(!keywords.length){await setError(workspaceId,"검색 키워드를 먼저 저장하세요.");return;}if(!clientId||!clientSecret){await setError(workspaceId,"NAVER_SEARCH_CLIENT_ID와 NAVER_SEARCH_CLIENT_SECRET이 설정되지 않았습니다.");return;}const keyword=keywords[randomInt(keywords.length)],start=randomInt(1,91),url=new URL("https://openapi.naver.com/v1/search/blog.json");url.searchParams.set("query",keyword);url.searchParams.set("display","10");url.searchParams.set("start",String(start));url.searchParams.set("sort","sim");try{const response=await fetch(url,{headers:{"X-Naver-Client-Id":clientId,"X-Naver-Client-Secret":clientSecret},cache:"no-store",signal:AbortSignal.timeout(8000)});if(!response.ok){const failure=await response.json().catch(()=>({})) as {errorCode?:string;errorMessage?:string};throw new Error(`네이버 검색 API ${response.status}${failure.errorCode?` · ${failure.errorCode}`:""}${failure.errorMessage?` · ${failure.errorMessage}`:""}`);}const data=await response.json() as {items?:{title?:string;link?:string;description?:string;bloggername?:string;postdate?:string}[]},items=(data.items??[]).filter(item=>item.link&&item.title),batch=randomUUID(),client=await db.connect();try{await client.query("BEGIN");for(const item of items){const published=item.postdate?.match(/^(\d{4})(\d{2})(\d{2})$/);await client.query(`INSERT INTO blog_discovery_items(workspace_id,batch_id,url,title,blogger_name,excerpt,published_on) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(workspace_id,url) DO UPDATE SET batch_id=EXCLUDED.batch_id,title=EXCLUDED.title,blogger_name=EXCLUDED.blogger_name,excerpt=EXCLUDED.excerpt,published_on=EXCLUDED.published_on,updated_at=now()`,[workspaceId,batch,item.link,clean(item.title??""),clean(item.bloggername??""),clean(item.description??""),published?`${published[1]}-${published[2]}-${published[3]}`:null]);}await client.query(`UPDATE blog_discovery_settings SET current_batch=$2,last_keyword=$3,last_error='',updated_at=now() WHERE workspace_id=$1`,[workspaceId,batch,keyword]);await client.query("COMMIT");}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}catch(error){const message=error instanceof Error?error.message:"검색 결과를 가져오지 못했습니다.";await recordAdminError("naver-blog-search",error,{workspaceId,keyword,httpEndpoint:"/v1/search/blog.json"});await setError(workspaceId,message);}}
async function setError(workspaceId:string,error:string){await db.query(`INSERT INTO blog_discovery_settings(workspace_id,last_error) VALUES($1,$2) ON CONFLICT(workspace_id) DO UPDATE SET last_error=EXCLUDED.last_error,updated_at=now()`,[workspaceId,error.slice(0,300)]);}
export async function setBlogDiscoveryItemStatus(id:string,workspaceId:string,status:"DONE"|"HIDDEN"){await db.query(`UPDATE blog_discovery_items SET status=$3,updated_at=now() WHERE id=$1 AND workspace_id=$2`,[id,workspaceId,status]);}
