export type GitHubRepository={owner:string;repo:string;url:string};
export type GitHubWorkflowRun={id:number;name:string;displayTitle:string;status:string;conclusion:string|null;branch:string;url:string;createdAt:string;runNumber:number};

function tokenFor(owner:string){const key=owner.toLowerCase();if(key==="alcove-world-official")return process.env.GITHUB_ACTIONS_TOKEN_ALCOVE;if(key==="tonolab")return process.env.GITHUB_ACTIONS_TOKEN_TONO;if(key==="parksujeong74")return process.env.GITHUB_ACTIONS_TOKEN_MANO;return process.env.GITHUB_ACTIONS_TOKEN;}
const headers=(owner:string)=>{const token=tokenFor(owner);return{Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28",...(token?{Authorization:`Bearer ${token}`}:{})};};
export const hasGitHubToken=(owner:string)=>Boolean(tokenFor(owner));

export function githubRepository(url:string):GitHubRepository|null{try{const parsed=new URL(url);if(parsed.hostname!=="github.com")return null;const [owner,rawRepo]=parsed.pathname.split("/").filter(Boolean);if(!owner||!rawRepo)return null;const repo=rawRepo.replace(/\.git$/i,"");return{owner,repo,url:`https://github.com/${owner}/${repo}`};}catch{return null;}}

export async function getLatestWorkflowRun(repository:GitHubRepository):Promise<{run:GitHubWorkflowRun|null;error:string|null}>{try{const response=await fetch(`https://api.github.com/repos/${encodeURIComponent(repository.owner)}/${encodeURIComponent(repository.repo)}/actions/runs?per_page=1`,{headers:headers(repository.owner),next:{revalidate:30}});if(response.status===404)return{run:null,error:"Repository not found or token cannot access it."};if(!response.ok)return{run:null,error:`GitHub API error (${response.status})`};const data=await response.json() as {workflow_runs?:Array<Record<string,unknown>>};const item=data.workflow_runs?.[0];if(!item)return{run:null,error:null};return{run:{id:Number(item.id),name:String(item.name??"Workflow"),displayTitle:String(item.display_title??""),status:String(item.status??"unknown"),conclusion:item.conclusion?String(item.conclusion):null,branch:String(item.head_branch??""),url:String(item.html_url??repository.url),createdAt:String(item.created_at??""),runNumber:Number(item.run_number??0)},error:null};}catch{return{run:null,error:"Could not reach GitHub."};}}

export async function rerunWorkflow(repository:GitHubRepository,runId:number){const response=await fetch(`https://api.github.com/repos/${encodeURIComponent(repository.owner)}/${encodeURIComponent(repository.repo)}/actions/runs/${runId}/rerun`,{method:"POST",headers:headers(repository.owner),cache:"no-store"});if(!response.ok)throw new Error(`GitHub rerun failed (${response.status})`);}
