import {createHmac} from "node:crypto";
import {db} from "@/lib/db";
export {n8nAuthorized} from "@/lib/internal-auth";
const webhookUrl=()=>process.env.N8N_AUTOMATION_WEBHOOK_URL?.trim();
const webhookSecret=()=>process.env.N8N_AUTOMATION_WEBHOOK_SECRET??"";

async function deliverEvent(event:{id:string;event_key:string;event_type:string;payload:unknown;created_at:Date}){const url=webhookUrl(),secret=webhookSecret();if(!url||!secret)return false;const body=JSON.stringify({id:Number(event.id),eventKey:event.event_key,eventType:event.event_type,occurredAt:event.created_at.toISOString(),payload:event.payload});const signature=createHmac("sha256",secret).update(body).digest("hex");try{const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json","x-mano-event":event.event_type,"x-mano-signature":`sha256=${signature}`},body,signal:AbortSignal.timeout(5000),cache:"no-store"});if(!response.ok)throw new Error(`n8n webhook ${response.status}`);await db.query(`UPDATE automation_events SET delivery_status='DELIVERED',delivered_at=now(),attempts=attempts+1,last_error='' WHERE id=$1`,[event.id]);return true;}catch(error){await db.query(`UPDATE automation_events SET attempts=attempts+1,last_error=$2 WHERE id=$1`,[event.id,error instanceof Error?error.message.slice(0,500):"delivery failed"]);return false;}}

export async function emitAutomationEvent(eventType:string,payload:Record<string,unknown>){const {rows}=await db.query(`INSERT INTO automation_events(event_type,payload) VALUES($1,$2::jsonb) RETURNING id,event_key,event_type,payload,created_at`,[eventType,JSON.stringify(payload)]);if(rows[0])await deliverEvent(rows[0]);}
export async function deliverPendingAutomationEvents(limit=25){const {rows}=await db.query(`SELECT id,event_key,event_type,payload,created_at FROM automation_events WHERE delivery_status='PENDING' AND attempts<20 ORDER BY created_at LIMIT $1`,[Math.min(Math.max(limit,1),100)]);let delivered=0;for(const event of rows)if(await deliverEvent(event))delivered++;return{attempted:rows.length,delivered};}
export async function retryAllPendingAutomationEvents(){await db.query(`UPDATE automation_events SET attempts=0,last_error='' WHERE delivery_status='PENDING' AND attempts>=20`);return deliverPendingAutomationEvents(100);}
export async function listAutomationEvents(after=0,limit=100){const {rows}=await db.query(`SELECT id,event_key,event_type,payload,delivery_status,attempts,created_at,delivered_at FROM automation_events WHERE id>$1 ORDER BY id LIMIT $2`,[Math.max(after,0),Math.min(Math.max(limit,1),500)]);return rows.map(r=>({id:Number(r.id),eventKey:r.event_key,eventType:r.event_type,payload:r.payload,deliveryStatus:r.delivery_status,attempts:r.attempts,occurredAt:r.created_at.toISOString(),deliveredAt:r.delivered_at?.toISOString()??null}));}
export async function listN8nRunnableTasks(){const {rows}=await db.query(`SELECT t.id,t.title,t.priority,t.due_at,w.name workspace_name,w.slug workspace_slug,count(tr.repository_id)::int repository_count FROM tasks t JOIN workspaces w ON w.id=t.workspace_id JOIN task_repositories tr ON tr.task_id=t.id WHERE w.ai_automation_enabled=true AND t.status='READY' AND t.due_at IS NOT NULL AND t.due_at<=now() AND NOT EXISTS(SELECT 1 FROM automation_executions e WHERE e.task_id=t.id AND e.status IN ('QUEUED','CLAIMED','RUNNING','REVIEW','REVISION_REQUESTED')) GROUP BY t.id,w.id ORDER BY t.due_at,t.created_at`);return rows.map(r=>({id:r.id,title:r.title,priority:r.priority,dueAt:r.due_at?.toISOString()??null,workspaceName:r.workspace_name,workspaceSlug:r.workspace_slug,repositoryCount:r.repository_count}));}
export async function getN8nIntegrationStatus(){const {rows}=await db.query(`SELECT count(*) FILTER(WHERE delivery_status='PENDING')::int pending,count(*) FILTER(WHERE delivery_status='DELIVERED')::int delivered,count(*) FILTER(WHERE delivery_status='PENDING' AND attempts>0)::int failed_delivery,max(delivered_at) last_delivered_at FROM automation_events`);const row=rows[0]??{};return{configured:Boolean(webhookUrl()&&webhookSecret()&&process.env.MANO_N8N_TOKEN),webhookConfigured:Boolean(webhookUrl()&&webhookSecret()),pending:row.pending??0,delivered:row.delivered??0,failedDelivery:row.failed_delivery??0,lastDeliveredAt:row.last_delivered_at?.toISOString()??null};}
export async function listRecentAutomationEvents(limit=30){const {rows}=await db.query(`SELECT id,event_key,event_type,payload,delivery_status,attempts,created_at,delivered_at FROM automation_events ORDER BY id DESC LIMIT $1`,[Math.min(Math.max(limit,1),100)]);return rows.map(r=>({id:Number(r.id),eventKey:r.event_key,eventType:r.event_type,payload:r.payload,deliveryStatus:r.delivery_status,attempts:r.attempts,occurredAt:r.created_at.toISOString(),deliveredAt:r.delivered_at?.toISOString()??null}));}
