import {db} from "@/lib/db";

export type T1Game={id:string;gameNumber:number;winner:"T1"|"OPPONENT"|null;side:"BLUE"|"RED"|null;t1Picks:string[];opponentPicks:string[];t1Bans:string[];opponentBans:string[]};
export type T1Match={id:string;tournament:string;opponent:string;scheduledAt:string;bestOf:number;status:"UPCOMING"|"LIVE"|"FINISHED";t1Score:number;opponentScore:number;sourceUrl:string;note:string;games:T1Game[]};
const list=(value:unknown)=>Array.isArray(value)?value.map(String):[];
export async function listT1Matches():Promise<T1Match[]>{const {rows}=await db.query(`SELECT m.*,COALESCE(json_agg(json_build_object('id',g.id,'gameNumber',g.game_number,'winner',g.winner,'side',g.side,'t1Picks',g.t1_picks,'opponentPicks',g.opponent_picks,'t1Bans',g.t1_bans,'opponentBans',g.opponent_bans) ORDER BY g.game_number) FILTER (WHERE g.id IS NOT NULL),'[]') games FROM t1_matches m LEFT JOIN t1_match_games g ON g.match_id=m.id GROUP BY m.id ORDER BY m.scheduled_at DESC`);return rows.map(row=>({id:row.id,tournament:row.tournament,opponent:row.opponent,scheduledAt:new Date(row.scheduled_at).toISOString(),bestOf:row.best_of,status:row.status,t1Score:row.t1_score,opponentScore:row.opponent_score,sourceUrl:row.source_url,note:row.note,games:list(row.games).length?row.games:[]}));}
export async function createT1Match(input:Omit<T1Match,"id"|"games">){await db.query(`INSERT INTO t1_matches(tournament,opponent,scheduled_at,best_of,status,t1_score,opponent_score,source_url,note) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[input.tournament,input.opponent,input.scheduledAt,input.bestOf,input.status,input.t1Score,input.opponentScore,input.sourceUrl,input.note]);}
export async function updateT1Match(id:string,input:Omit<T1Match,"id"|"games">){await db.query(`UPDATE t1_matches SET tournament=$2,opponent=$3,scheduled_at=$4,best_of=$5,status=$6,t1_score=$7,opponent_score=$8,source_url=$9,note=$10,updated_at=now() WHERE id=$1`,[id,input.tournament,input.opponent,input.scheduledAt,input.bestOf,input.status,input.t1Score,input.opponentScore,input.sourceUrl,input.note]);}
export async function deleteT1Match(id:string){await db.query(`DELETE FROM t1_matches WHERE id=$1`,[id]);}
export async function upsertT1Game(input:{matchId:string;gameNumber:number;winner:string|null;side:string|null;t1Picks:string[];opponentPicks:string[];t1Bans:string[];opponentBans:string[]}){await db.query(`INSERT INTO t1_match_games(match_id,game_number,winner,side,t1_picks,opponent_picks,t1_bans,opponent_bans) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(match_id,game_number) DO UPDATE SET winner=EXCLUDED.winner,side=EXCLUDED.side,t1_picks=EXCLUDED.t1_picks,opponent_picks=EXCLUDED.opponent_picks,t1_bans=EXCLUDED.t1_bans,opponent_bans=EXCLUDED.opponent_bans,updated_at=now()`,[input.matchId,input.gameNumber,input.winner,input.side,input.t1Picks,input.opponentPicks,input.t1Bans,input.opponentBans]);}
export async function deleteT1Game(id:string){await db.query(`DELETE FROM t1_match_games WHERE id=$1`,[id]);}
