import { notFound } from "next/navigation";
import { deleteEventAction, updateEventAction } from "@/app/personal/actions";
import { getCalendarEvent, listWorkspaces } from "@/lib/automation-repository";
import { EventColorPicker } from "@/components/event-color-picker";
import { EventScheduleFields } from "@/components/event-schedule-fields";

export const dynamic="force-dynamic";
const local=(iso:string|null,allDay:boolean)=>{if(!iso)return "";const value=new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(iso));return allDay?value.slice(0,10):value.replace(" ","T");};
export default async function EventPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const [event,workspaces]=await Promise.all([getCalendarEvent(id),listWorkspaces()]);if(!event)notFound();return <><header className="page-head"><div><p className="eyebrow">CALENDAR EVENT</p><h1>{event.title}</h1><p>Edit the schedule, recurrence, color, and Workspace association.</p></div><a className="text-link" href="/calendar">← Calendar</a></header><form action={updateEventAction} className="editor-section event-editor"><input type="hidden" name="id" value={event.id}/><div className="form-grid"><label><span>Title</span><input name="title" defaultValue={event.title} required/></label><label><span>Workspace</span><select name="workspaceId" defaultValue={event.workspaceId??""}><option value="">No workspace</option>{workspaces.map((w)=><option value={w.id} key={w.id}>{w.name}</option>)}</select></label><EventScheduleFields initialStart={local(event.startsAt,false)} initialEnd={local(event.endsAt,false)} initialAllDay={event.allDay}/><label><span>Repeat</span><select name="recurrence" defaultValue={event.recurrence}><option value="NONE">Does not repeat</option><option value="YEARLY">Every year</option></select></label><EventColorPicker defaultValue={event.color}/><label><span>Description</span><textarea name="description" defaultValue={event.description}/></label></div><div className="editor-actions"><button>Save event</button></div></form><form action={deleteEventAction} className="danger-zone"><input type="hidden" name="id" value={event.id}/><span>Deleting an event cannot be undone.</span><button className="danger">Delete event</button></form></>}
