import { notFound } from "next/navigation";
import { deleteEventAction, updateEventAction } from "@/app/personal/actions";
import { EventColorPicker } from "@/components/event-color-picker";
import { EventScheduleFields } from "@/components/event-schedule-fields";
import { getCalendarEvent, listWorkspaces } from "@/lib/automation-repository";

export const dynamic="force-dynamic";
const local=(iso:string|null)=>{if(!iso)return "";return new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date(iso)).replace(" ","T");};
const safeReturn=(value?:string)=>value&&/^\/calendar(?:\?month=\d{4}-\d{2})?$/.test(value)?value:"/calendar";

export default async function EventPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{returnTo?:string}>}){const {id}=await params,returnTo=safeReturn((await searchParams).returnTo),[event,workspaces]=await Promise.all([getCalendarEvent(id),listWorkspaces()]);if(!event)notFound();return <><header className="page-head"><div><p className="eyebrow">CALENDAR EVENT</p><h1>{event.title}</h1><p>Edit the schedule, recurrence, color, and Workspace association.</p></div><a className="text-link" href={returnTo}>← Calendar</a></header><form action={updateEventAction} className="editor-section event-editor"><input type="hidden" name="id" value={event.id}/><input type="hidden" name="returnTo" value={returnTo}/><div className="form-grid"><label><span>Title</span><input name="title" defaultValue={event.title} required/></label><label><span>Workspace</span><select name="workspaceId" defaultValue={event.workspaceId??""}><option value="">No workspace</option>{workspaces.map((workspace)=><option value={workspace.id} key={workspace.id}>{workspace.name}</option>)}</select></label><EventScheduleFields initialStart={local(event.startsAt)} initialEnd={local(event.endsAt)} initialAllDay={event.allDay}/><label><span>Repeat</span><select name="recurrence" defaultValue={event.recurrence}><option value="NONE">Does not repeat</option><option value="YEARLY">Every year</option></select></label><EventColorPicker defaultValue={event.color}/><label><span>Description</span><textarea name="description" defaultValue={event.description}/></label></div><div className="editor-actions"><button>Save event</button></div></form><form action={deleteEventAction} className="danger-zone"><input type="hidden" name="id" value={event.id}/><input type="hidden" name="returnTo" value={returnTo}/><span>Deleting an event cannot be undone.</span><button className="danger">Delete event</button></form></>}
