#!/bin/bash

cd "$(dirname "$0")/../.." 

if [ -f .env.local ]; then
    export $(grep -v '^#' .env.local | xargs)
fi

export VAULT_TOKEN=$VAULT_TOKEN
export VAULT_ADDR=$VAULT_ADDR
export VAULT_NAME=$VAULT_NAME

vault kv put secret/$VAULT_NAME \
    SERVICE_WEB_PORT=$SERVICE_WEB_PORT \
    SERVICE_API_PORT=$SERVICE_API_PORT \
    SERVICE_DESKTOP_PORT=$SERVICE_DESKTOP_PORT \
    SERVICE_MOBILE_PORT=$SERVICE_MOBILE_PORT \
    SERVICE_API_URL=$SERVICE_API_URL \
    POSTGRES_DB=$POSTGRES_DB \
    POSTGRES_USER=$POSTGRES_USER \
    POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    MONGO_ROOT_USER=$MONGO_ROOT_USER \
    MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD \
    MINIO_ROOT_USER=$MINIO_ROOT_USER \
    MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD \
    RABBITMQ_USER=$RABBITMQ_USER \
    RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD \
    RABBITMQ_VHOST=$RABBITMQ_VHOST

vault kv get secret/my_own_note_local