import Link from "next/link";
import { notFound } from "next/navigation";
import { workspaceDetails } from "@/config/workspace-details";
import { listTasks, listWorkspaces } from "@/lib/automation-repository";

export const dynamic="force-dynamic";
export default async function WorkspacePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const [workspaces,tasks]=await Promise.all([listWorkspaces(),listTasks(slug)]);const workspace=workspaces.find((item)=>item.slug===slug),detail=workspaceDetails[slug];if(!workspace||!detail)notFound();return <><header className="page-head workspace-hero"><div><p className="eyebrow">WORKSPACE</p><h1>{workspace.name}</h1><p>{detail.summary}</p></div><Link className="text-link" href="/workspaces">← All workspaces</Link></header>
  <section className="workspace-overview"><article className="workspace-purpose"><p className="eyebrow">ROLE</p><h2>What this space is for</h2><p>{detail.purpose}</p><div className="workspace-links">{workspace.links.map((link)=><a href={link.url} target="_blank" rel="noreferrer" key={link.url}>{link.label} ↗</a>)}</div></article><article className="workspace-stat"><span>Open context</span><strong>{tasks.filter((task)=>task.status!=="DONE").length}</strong><p>{workspace.taskCount} total Tasks</p><Link href={`/automation/tasks?workspace=${slug}`}>View all Tasks →</Link></article></section>
  <section className="workspace-detail-grid"><article><p className="eyebrow">RESPONSIBILITIES</p><h2>What belongs here</h2><ul>{detail.responsibilities.map((item)=><li key={item}>{item}</li>)}</ul></article><article><p className="eyebrow">WORKFLOW</p><h2>Recommended flow</h2><ol>{detail.workflow.map((item,index)=><li key={item}><span>{index+1}</span>{item}</li>)}</ol></article></section>
  <section className="workspace-guidance"><div><p className="eyebrow">TASK GUIDANCE</p><h2>When to create a Task</h2><p>{detail.taskGuidance}</p></div><Link className="button-link" href={`/automation/tasks?workspace=${slug}`}>Create or view Tasks</Link></section>
  <section className="section-head"><div><p className="eyebrow">RECENT WORK</p><h2>Latest Tasks</h2></div><Link href={`/automation/tasks?workspace=${slug}`}>View all →</Link></section><section className="data-list">{tasks.slice(0,5).map((task)=><article key={task.id}><div className="data-main"><div className="data-meta"><span>{task.status.replaceAll("_"," ")}</span><span>{task.priority}</span></div><h2><Link href={`/automation/tasks/${task.id}`}>{task.title}</Link></h2><p>{task.description||"No description"}</p></div>{task.dueAt&&<small>Due {new Date(task.dueAt).toLocaleString("en-GB",{timeZone:"Asia/Seoul"})}</small>}</article>)}</section>{tasks.length===0&&<div className="empty-state">No Tasks in this Workspace yet.</div>}
  </>}
