"use server";

import { revalidatePath } from "next/cache";
import { createAutomationInstruction, createAutomationRepository, createWorkspacePostit, createWorkspaceTodo, createWorkspaceTodoCategory, deleteAutomationInstruction, deleteAutomationRepository, deleteWorkspacePostit, deleteWorkspaceTodo, deleteWorkspaceTodoCategory, moveWorkspaceTodoCategory, updateAutomationInstruction, updateAutomationRepository, updateWorkspace, updateWorkspaceAutomation, updateWorkspacePostit, updateWorkspaceTodo, updateWorkspaceTodoCategory, updateWorkspaceTodoCompleted } from "@/lib/automation-repository";
import type { WorkspaceType } from "@/lib/automation-types";
import { listWorkspaces } from "@/lib/automation-repository";
import { githubRepository, managedGitHubRepositories, rerunWorkflow } from "@/lib/github-actions";
import {rerollBlogDiscovery,saveBlogDiscoveryExclusions,saveBlogDiscoveryKeywords,setBlogDiscoveryItemStatus} from "@/lib/blog-discovery";

const value=(data:FormData,name:string)=>String(data.get(name)??"").trim();
const lines=(input:string)=>input.split("\n").map((line)=>line.trim()).filter(Boolean);
function links(input:string){return lines(input).flatMap((line)=>{const separator=line.indexOf("|");if(separator<1)return[];const label=line.slice(0,separator).trim(),url=line.slice(separator+1).trim();try{const parsed=new URL(url);return label&&["http:","https:"].includes(parsed.protocol)?[{label,url}]:[];}catch{return[];}});}

export async function updateWorkspaceAction(data:FormData){const id=value(data,"id"),slug=value(data,"slug"),name=value(data,"name");if(!id||!slug||!name)return;await updateWorkspace(id,{name,description:value(data,"description"),links:links(value(data,"links")),details:{summary:value(data,"summary"),purpose:value(data,"purpose"),responsibilities:lines(value(data,"responsibilities")),workflow:lines(value(data,"workflow")),taskGuidance:value(data,"taskGuidance")}});revalidatePath("/workspaces");revalidatePath(`/workspaces/${slug}`);}
const refresh=(slug:string)=>revalidatePath(`/workspaces/${slug}`);
const postitColor=(data:FormData)=>["yellow","blue","pink","purple","green"].includes(value(data,"color"))?value(data,"color"):"yellow";
export async function createPostitAction(data:FormData){const workspaceId=value(data,"workspaceId"),slug=value(data,"slug"),content=value(data,"content");if(!workspaceId||!slug||!content)return;await createWorkspacePostit({workspaceId,categoryId:value(data,"categoryId")||null,title:value(data,"title"),content,color:postitColor(data)});refresh(slug);}
export async function updatePostitAction(data:FormData){const id=value(data,"id"),slug=value(data,"slug"),content=value(data,"content");if(!id||!slug||!content)return;await updateWorkspacePostit(id,{categoryId:value(data,"categoryId")||null,title:value(data,"title"),content,color:postitColor(data)});refresh(slug);}
export async function deletePostitAction(data:FormData){const id=value(data,"id"),slug=value(data,"slug");if(!id||!slug)return;await deleteWorkspacePostit(id);refresh(slug);}
export async function saveBlogDiscoveryKeywordsAction(data:FormData){const workspaceId=value(data,"workspaceId"),keywords=lines(value(data,"keywords")),recentYears=value(data,"recentYears")==="2"?2:1;if(!workspaceId)return;await saveBlogDiscoveryKeywords(workspaceId,keywords,recentYears);refresh("blog");}
export async function saveBlogDiscoveryExclusionsAction(data:FormData){const workspaceId=value(data,"workspaceId");if(!workspaceId)return;const upload=data.get("exclusionOpml"),opmlIds=upload instanceof File&&upload.size?(await upload.text()).match(/htmlUrl="([^"]+)"/g)?.map((entry)=>entry.slice(9,-1))??[]:[];await saveBlogDiscoveryExclusions(workspaceId,[...lines(value(data,"exclusionIds")),...opmlIds]);refresh("blog");}
export async function rerollBlogDiscoveryAction(data:FormData){const workspaceId=value(data,"workspaceId"),rawMode=value(data,"discoveryMode"),mode=rawMode==="MUTUAL"?"MUTUAL":rawMode==="TAGS_ONLY"?"TAGS_ONLY":"NORMAL";if(!workspaceId)return;await rerollBlogDiscovery(workspaceId,mode);refresh("blog");}
export async function completeBlogDiscoveryItemAction(data:FormData){const id=value(data,"id"),workspaceId=value(data,"workspaceId");if(!id||!workspaceId)return;await setBlogDiscoveryItemStatus(id,workspaceId,"DONE");refresh("blog");}
export async function hideBlogDiscoveryItemAction(data:FormData){const id=value(data,"id"),workspaceId=value(data,"workspaceId");if(!id||!workspaceId)return;await setBlogDiscoveryItemStatus(id,workspaceId,"HIDDEN");refresh("blog");}
export async function excludeBlogDiscoveryAction(data:FormData){const id=value(data,"id"),workspaceId=value(data,"workspaceId");if(!id||!workspaceId)return;await setBlogDiscoveryItemStatus(id,workspaceId,"NEIGHBOR");refresh("blog");}
export async function createTodoCategoryAction(data:FormData){const workspaceId=value(data,"workspaceId"),slug=value(data,"slug"),name=value(data,"name");if(!workspaceId||!slug||!name)return;await createWorkspaceTodoCategory(workspaceId,name);refresh(slug);}
export async function updateTodoCategoryAction(data:FormData){const id=value(data,"id"),slug=value(data,"slug"),name=value(data,"name");if(!id||!slug||!name)return;await updateWorkspaceTodoCategory(id,name);refresh(slug);}
export async function moveTodoCategoryAction(data:FormData){const id=value(data,"id"),workspaceId=value(data,"workspaceId"),slug=value(data,"slug"),direction=value(data,"direction");if(!id||!workspaceId||!slug||!["up","down"].includes(direction))return;await moveWorkspaceTodoCategory(id,workspaceId,direction as "up"|"down");refresh(slug);}
export async function deleteTodoCategoryAction(data:FormData){const id=value(data,"id"),slug=value(data,"slug");if(!id||!slug)return;await deleteWorkspaceTodoCategory(id);refresh(slug);}
export async function createTodoAction(data:FormData){const categoryId=value(data,"categoryId"),slug=value(data,"slug"),title=value(data,"title");if(!categoryId||!slug||!title)return;await createWorkspaceTodo(categoryId,title);refresh(slug);}
export async function updateTodoAction(data:FormData){const id=value(data,"id"),categoryId=value(data,"categoryId"),slug=value(data,"slug"),title=value(data,"title");if(!id||!categoryId||!slug||!title)return;await updateWorkspaceTodo(id,{categoryId,title});refresh(slug);}
export async function toggleTodoAction(data:FormData){const id=value(data,"id"),slug=value(data,"slug");if(!id||!slug)return;await updateWorkspaceTodoCompleted(id,value(data,"completed")==="true");refresh(slug);}
export async function deleteTodoAction(data:FormData){const id=value(data,"id"),slug=value(data,"slug");if(!id||!slug)return;await deleteWorkspaceTodo(id);refresh(slug);}
const refreshAutomation=(slug:string)=>{refresh(slug);revalidatePath(`/workspaces/${slug}/automation`);};
export async function updateWorkspaceAutomationAction(data:FormData){const id=value(data,"workspaceId"),slug=value(data,"slug"),workspaceType=value(data,"workspaceType") as WorkspaceType;if(!id||!slug||!["APPLICATION","INFRASTRUCTURE","CONTENT","GENERAL"].includes(workspaceType))return;await updateWorkspaceAutomation(id,{enabled:data.get("enabled")==="on",workspaceType});refreshAutomation(slug);}
function githubParts(url:string){try{const parsed=new URL(url);if(parsed.hostname!=="github.com")return null;const [owner,repo]=parsed.pathname.replace(/^\//,"").replace(/\.git$/,"").split("/");return owner&&repo?{owner,repo}:null;}catch{return null;}}
export async function createAutomationRepositoryAction(data:FormData){const workspaceId=value(data,"workspaceId"),slug=value(data,"slug"),gitUrl=value(data,"gitUrl"),parts=githubParts(gitUrl);if(!workspaceId||!slug||!parts)return;await createAutomationRepository({workspaceId,name:value(data,"name")||parts.repo,owner:parts.owner,repo:parts.repo,gitUrl,defaultBranch:value(data,"defaultBranch")||"main"});refreshAutomation(slug);}
export async function updateAutomationRepositoryAction(data:FormData){const id=value(data,"id"),slug=value(data,"slug"),name=value(data,"name"),gitUrl=value(data,"gitUrl"),parts=githubParts(gitUrl);if(!id||!slug||!name||!parts)return;await updateAutomationRepository(id,{name,owner:parts.owner,repo:parts.repo,gitUrl,defaultBranch:value(data,"defaultBranch")||"main",enabled:data.get("enabled")==="on"});refreshAutomation(slug);}
export async function deleteAutomationRepositoryAction(data:FormData){const id=value(data,"id"),slug=value(data,"slug");if(!id||!slug)return;await deleteAutomationRepository(id);refreshAutomation(slug);}
export async function createAutomationInstructionAction(data:FormData){const workspaceId=value(data,"workspaceId"),slug=value(data,"slug"),scope=value(data,"scope"),repositoryId=value(data,"repositoryId")||null,title=value(data,"title"),content=value(data,"content");if(!workspaceId||!slug||!title||!content||!["WORKSPACE","REPOSITORY"].includes(scope)||(scope==="REPOSITORY"&&!repositoryId))return;await createAutomationInstruction({scope:scope as "WORKSPACE"|"REPOSITORY",workspaceId,repositoryId,title,content});refreshAutomation(slug);}
export async function updateAutomationInstructionAction(data:FormData){const id=value(data,"id"),slug=value(data,"slug"),title=value(data,"title"),content=value(data,"content");if(!id||!slug||!title||!content)return;await updateAutomationInstruction(id,{title,content,enabled:data.get("enabled")==="on"});refreshAutomation(slug);}
export async function deleteAutomationInstructionAction(data:FormData){const id=value(data,"id"),slug=value(data,"slug");if(!id||!slug)return;await deleteAutomationInstruction(id);refreshAutomation(slug);}
export async function rerunGitHubWorkflowAction(data:FormData){const workspaceId=value(data,"workspaceId"),slug=value(data,"slug"),owner=value(data,"owner"),repo=value(data,"repo"),runId=Number(value(data,"runId"));if(!owner||!repo||!Number.isSafeInteger(runId)||runId<=0)return;const managed=managedGitHubRepositories.find((item)=>item.owner.toLowerCase()===owner.toLowerCase()&&item.repo.toLowerCase()===repo.toLowerCase());const workspace=workspaceId&&slug?(await listWorkspaces()).find((item)=>item.id===workspaceId&&item.slug===slug):null;const linked=workspace?.links.map((link)=>githubRepository(link.url)).find((item)=>item?.owner.toLowerCase()===owner.toLowerCase()&&item.repo.toLowerCase()===repo.toLowerCase());const repository=managed??linked;if(!repository)return;await rerunWorkflow(repository,runId);revalidatePath("/github-actions");if(slug)refresh(slug);}
