import Link from "next/link";
import { notFound } from "next/navigation";
import { createAutomationInstructionAction, createAutomationRepositoryAction, deleteAutomationInstructionAction, deleteAutomationRepositoryAction, updateAutomationInstructionAction, updateAutomationRepositoryAction, updateWorkspaceAutomationAction } from "@/app/workspaces/actions";
import { listAutomationInstructions, listAutomationRepositories, listWorkspaces } from "@/lib/automation-repository";

export const dynamic="force-dynamic";

export default async function WorkspaceAutomationPage({params}:{params:Promise<{slug:string}>}){
  const {slug}=await params;
  const workspace=(await listWorkspaces()).find((item)=>item.slug===slug);
  if(!workspace)notFound();
  const [repositories,instructions]=await Promise.all([listAutomationRepositories(workspace.id),listAutomationInstructions(workspace.id)]);
  return <>
    <header className="page-head"><div><p className="eyebrow">{workspace.name} · PROJECT CONTROL</p><h1>AI Automation</h1><p>프로젝트 지침과 저장소를 연결합니다. Task 하나가 여러 저장소를 대상으로 실행될 수 있습니다.</p></div><Link className="text-link" href={`/workspaces/${slug}`}>← Workspace</Link></header>
    <section className="control-section"><div className="section-head"><div><p className="eyebrow">PROJECT</p><h2>Automation mode</h2></div></div><form action={updateWorkspaceAutomationAction} className="automation-settings"><input type="hidden" name="workspaceId" value={workspace.id}/><input type="hidden" name="slug" value={slug}/><label className="check-line"><input type="checkbox" name="enabled" defaultChecked={workspace.aiAutomationEnabled}/><span>AI automation enabled</span></label><label><span>Project type</span><select name="workspaceType" defaultValue={workspace.workspaceType}><option value="APPLICATION">Application</option><option value="INFRASTRUCTURE">Infrastructure</option><option value="CONTENT">Content</option><option value="GENERAL">General</option></select></label><button>Save</button></form>{workspace.workspaceType==="INFRASTRUCTURE"&&<p className="safety-note">Infrastructure 모드는 코드와 설정의 PR 생성까지만 기본 허용합니다. 배포·마이그레이션·볼륨 및 시스템 변경은 추후 별도 승인 단계로 분리됩니다.</p>}</section>
    <section className="control-section"><div className="section-head"><div><p className="eyebrow">REPOSITORIES</p><h2>Connected repositories</h2></div><span>{repositories.length} repositories</span></div><form action={createAutomationRepositoryAction} className="control-create"><input type="hidden" name="workspaceId" value={workspace.id}/><input type="hidden" name="slug" value={slug}/><input name="name" placeholder="Display name (optional)"/><input name="gitUrl" type="url" required placeholder="https://github.com/owner/repository"/><input name="defaultBranch" defaultValue="main" required placeholder="Default branch"/><button>Add repository</button></form><div className="control-list">{repositories.map((repository)=><details key={repository.id}><summary><span><strong>{repository.name}</strong><small>{repository.owner}/{repository.repo} · {repository.defaultBranch}</small></span><em className={repository.enabled?"enabled":"disabled"}>{repository.enabled?"enabled":"disabled"}</em></summary><form action={updateAutomationRepositoryAction} className="control-editor"><input type="hidden" name="id" value={repository.id}/><input type="hidden" name="slug" value={slug}/><label><span>Name</span><input name="name" defaultValue={repository.name} required/></label><label><span>GitHub URL</span><input name="gitUrl" type="url" defaultValue={repository.gitUrl} required/></label><label><span>Default branch</span><input name="defaultBranch" defaultValue={repository.defaultBranch} required/></label><label className="check-line"><input type="checkbox" name="enabled" defaultChecked={repository.enabled}/> Enabled</label><button>Save</button></form><form action={deleteAutomationRepositoryAction} className="danger-row"><input type="hidden" name="id" value={repository.id}/><input type="hidden" name="slug" value={slug}/><button>Delete repository</button></form></details>)}</div></section>
    <section className="control-section"><div className="section-head"><div><p className="eyebrow">INSTRUCTIONS</p><h2>AI instruction layers</h2></div></div><p className="section-copy">실행할 때 Global → Workspace → Repository → Task 순으로 합쳐집니다. Global 지침은 이 화면에서 읽기만 가능합니다.</p><form action={createAutomationInstructionAction} className="instruction-create"><input type="hidden" name="workspaceId" value={workspace.id}/><input type="hidden" name="slug" value={slug}/><select name="scope" defaultValue="WORKSPACE"><option value="WORKSPACE">Workspace</option><option value="REPOSITORY">Repository</option></select><select name="repositoryId" defaultValue=""><option value="">No repository</option>{repositories.map((repository)=><option key={repository.id} value={repository.id}>{repository.name}</option>)}</select><input name="title" required placeholder="Instruction title"/><textarea name="content" required placeholder="AI가 이 프로젝트 또는 저장소에서 항상 따라야 할 지침"/><button>Add instruction</button></form><div className="control-list">{instructions.map((instruction)=><details key={instruction.id}><summary><span><strong>{instruction.title}</strong><small>{instruction.scope}{instruction.repositoryName?` · ${instruction.repositoryName}`:""}</small></span><em className={instruction.enabled?"enabled":"disabled"}>{instruction.enabled?"enabled":"disabled"}</em></summary>{instruction.scope==="GLOBAL"?<pre className="instruction-preview">{instruction.content}</pre>:<><form action={updateAutomationInstructionAction} className="control-editor instruction-editor"><input type="hidden" name="id" value={instruction.id}/><input type="hidden" name="slug" value={slug}/><label><span>Title</span><input name="title" defaultValue={instruction.title} required/></label><label><span>Instruction</span><textarea name="content" defaultValue={instruction.content} required/></label><label className="check-line"><input type="checkbox" name="enabled" defaultChecked={instruction.enabled}/> Enabled</label><button>Save</button></form><form action={deleteAutomationInstructionAction} className="danger-row"><input type="hidden" name="id" value={instruction.id}/><input type="hidden" name="slug" value={slug}/><button>Delete instruction</button></form></>}</details>)}</div></section>
  </>;
}
