apiVersion: 1

contactPoints:
  - orgId: 1
    name: Slack Alcove
    receivers:
      - uid: slack-alcove
        type: slack
        disableResolveMessage: false
        settings:
          username: Grafana
          title: |
            {{ if eq .Status "firing" }}🚨{{ else }}✅{{ end }} {{ template "default.title" . }}
          text: |
            {{ template "default.message" . }}
        secureSettings:
          url: $SLACK_ALCOVE_WEBHOOK_URL

  - orgId: 1
    name: Discord Tono
    receivers:
      - uid: discord-tono
        type: discord
        disableResolveMessage: false
        settings:
          use_discord_username: false
          message: |
            {{ template "default.message" . }}
        secureSettings:
          url: $DISCORD_TONO_WEBHOOK_URL

  - orgId: 1
    name: Project Shared Server
    receivers:
      - uid: slack-server-alcove
        type: slack
        disableResolveMessage: false
        settings:
          username: Grafana
          title: |
            {{ if eq .Status "firing" }}🚨{{ else }}✅{{ end }} {{ template "default.title" . }}
          text: |
            {{ template "default.message" . }}
        secureSettings:
          url: $SLACK_ALCOVE_WEBHOOK_URL
      - uid: discord-server-tono
        type: discord
        disableResolveMessage: false
        settings:
          use_discord_username: false
          message: |
            {{ template "default.message" . }}
        secureSettings:
          url: $DISCORD_TONO_WEBHOOK_URL

policies:
  - orgId: 1
    receiver: Project Shared Server
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: Slack Alcove
        object_matchers:
          - [alert_scope, =, alcove]
        group_by: [alertname]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
      - receiver: Discord Tono
        object_matchers:
          - [alert_scope, =, tono]
        group_by: [alertname]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 1h
      - receiver: Project Shared Server
        object_matchers:
          - [alert_scope, =, shared_server]
        group_by: [alertname]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 2h
